shellEmulator: true

trustPolicy: no-downgrade

allowBuilds:
  '@parcel/watcher': true
  '@tailwindcss/oxide': true
  better-sqlite3: true
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true

catalogs:
  dev:
    '@favorodera/eslint-config': ^1.0.4
    '@types/node': ^26.2.0
    '@typescript/native-preview': 7.0.0-dev.20260707.2
    '@vitest/ui': 4.1.10
    db0: ^0.3.4

    eslint: ^10.8.1
    relizy: ^1.4.9
    tsdown: ^0.22.14
    typescript: ^6.0.3
    vitest: ^4.1.10
  vendor:
    zod: ^4.4.3

peerDependencyRules:
  allowedVersions:
    typescript: '6'
    vite: '8'
