name: CI

on: [push, pull_request]

jobs:
  ci:
    name: Lint, Typecheck, Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.3
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v6.0.8

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Test
        run: pnpm test

  preview:
    name: Publish Preview Packages
    needs: ci
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.3

      - name: Setup pnpm
        uses: pnpm/action-setup@v6.0.8

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Packages
        run: pnpm build

      - name: Publish Preview to pkg-pr-new
        run: pnpm dlx pkg-pr-new publish
